[WIP] Executor arrays
cmjava2023/vm pull request #58
Opened 2023-12-05 14:18 UTC by JonaZz747

- Datastructures (on locals, stack, ...) + opCodes for
- primitive Arrays
- Object Arrays
- Multidim Arrays

2023-12-05 18:37 UTC, liketechnik commented
In it's current state this does not cover all array opcodes (in particular most opcodes dealing with primitve datatype arrays + `newarray` + `multianewarray` are still missing), but the stuff that's implemented is already finished.

TL~DR: this can be merged now, if you don't have anything to (re)consider during review. (So that the parser team can use the changed opcode definitions)

2023-12-06 07:54 UTC, Aetlam requested changes

2023-12-06 07:54 UTC, Aetlam commented on src/class/builtin_classes/array.rs
> +        "[C"
This seems like a coppy paste error should be [D

2023-12-06 07:54 UTC, Aetlam commented on src/class/builtin_classes/array.rs
> +        "[C"
same here

2023-12-06 08:16 UTC, liketechnik commented
Failures kommen durch den merge, ich kümmere mich gleich um den rebase

2023-12-06 13:00 UTC, merged